### ISSUE TITLE
multiplayer ?

### ISSUE THREAD

**Issue by dcsan** [RSamaium/RPG-JS#107]
I'm wondering how much the system is designed for multiplayer? I see "MMO" in the name and also some references in the docs, but wondering if there are server features to support this?

**Comment by RSamaium** [comment]
Hello,

Your question is to know the benchmarks? What type of server is needed to support the MMO?

If that's your question, there have been tests but no fixed conclusions on the subject

https://github.com/RSamaium/RPG-JS/blob/v3/tests/load-testing/socket.yml

It has been found that the server can have trouble holding the load if a lot of people are on the same map. But, I don't have any precise metrics at the moment

**Comment by dcsan** [comment]
not benchmarking, more about what APIs there are? 

eg does the server display multiple players on the same map? I wasn't quite sure after checking the tutorial but reading from the above i guess it does? 

update: just tried the demo in two browsers and i can see my players bump around, so i guess it is MP!

for example, can you interact with other players?
are game items "per player" shared or does each player have their own map and state?

I see there's a type of pub/sub for events
https://docs.rpgjs.dev/classes/world.html#api

so the mechanism is that you would subscribe to the events per room or ... map?
sorry just trying to understand the model here.

also i see you 'abstract' the database. the API looks nice, but i wonder what is backing it if there are no requirements. if its in-memory, is it persisted? if its just file system, then performance maybe a concern...
ie will it scale to 100 users ok? 5,000 ?

**Comment by RSamaium** [comment]
Okay,

Yes, RPGJS allows to make MMORPG and its structure was thought to favour this type of game. For example, the system optimises the use of bandwidth, or there is a prediction of player positions on the client side to make the moves smooth

Then you can decide how the players interact with each other. Indeed, the RpgWorld class allows you to get other players (on the map or in the whole world). For example, you can decide, by pressing a key, that all players around you lose HP.

The map is shared with all players and kept in memory. The events on it are also shared with all players. For example, in the demo, everyone sees the characters move in the same way

However, you can create player-specific events to create a scenario in the game. For example, each player can open the chest in the demo, not just a single player. It could be thought of as containing a key, which each player must possess to continue the scenario

> so the mechanism is that you would subscribe to the events per room or ... map?

In RPGJS, a map is a room. All data on a map is shared with all players on that map

The database is in memory. And nothing is persistent. If you restart the server, you lose data like the player's level, items, etc.

> also i see you 'abstract' the database. the API looks nice, but i wonder what is backing it if there are no requirements. if its in-memory, is it persisted? if its just file system, then performance maybe a concern...

To make it persistent, you have to set up a save (https://docs.rpgjs.dev/commands/common.html#save-progress). it returns a snapshot of the player in JSON format. It then needs to be put into a database. If this seems too complicated, you should know that plugins exist (https://docs.rpgjs.dev/plugins/title-screen.html). The plugin uses MongoDB and requires registration before playing the game. As soon as you use `player.save()` on the server side (for example, before entering a dungeon), a persistent save is made to the database

> ie will it scale to 100 users ok? 5,000 ?

It will depend on the server. But I don't have an exact measurement on this yet. In any case, it is suitable for thousands of players
