### ISSUE TITLE
lerna bootstrap issue

### ISSUE THREAD

**Issue by dkatashev** [RSamaium/RPG-JS#109]
Hello @RSamaium,
You have done a great job.
I would like to help with the development of the project.
I tried to initialize the project but I get the error:

```
lerna bootstrap
lerna notice cli v4.0.0
lerna info Bootstrapping 25 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@rpgjs/title-screen'
lerna ERR! npm install stderr:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @rpgjs/client@3.0.0-beta.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

Update:
- I found that lerna packages have the wrong version in package.json
- Could be a problem with generated package-lock.json inside @rpgjs/title-screen

**Comment by RSamaium** [comment]
Hey,

Sorry for my late reply (I was quite busy last month). 
I have updated the packages so that the installation with lerna can go well.  Here are the instructions below

To contribute to the developments, install the sources locally:

```
git clone https://github.com/RSamaium/RPG-JS.git
npm install
npm run dev
```

> It only works on NodeJS version 14. You can help with the development to make it work on version 16 (you will have to update Webpack and Node SASS in packages/compiler)
> The installation is a bit long, don't worry!
