### ISSUE TITLE
Error TS2307: Cannot find module '@rp gjs/common' or its corresponding type declarations.

### ISSUE THREAD

**Issue by cryptonft** [RSamaium/RPG-JS#112]
Getting this error across multiple files that require it

**Comment by cryptonft** [comment]
[watch:client] src/clientEntryPoint.ts(1,68): error TS2307: Cannot find module '
@rpgjs/common' or its corresponding type declarations.
[watch:client] src/Effects/Animation.ts(1,23): error TS2307: Cannot find module 
'@rpgjs/common' or its corresponding type declarations.
[watch:client] src/index.ts(1,80): error TS2307: Cannot find module '@rpgjs/comm
on' or its corresponding type declarations.
[watch:client] src/index.ts(3,28): error TS2307: Cannot find module '@rpgjs/comm
on' or its corresponding type declarations.
[watch:client] src/KeyboardControls.ts(1,23): error TS2307: Cannot find module '
@rpgjs/common' or its corresponding type declarations.
[watch:client] src/Presets/AnimationSpritesheet.ts(1,27): error TS2307: Cannot f
ind module '@rpgjs/common' or its corresponding type declarations.
[watch:client] src/Renderer.ts(3,39): error TS2307: Cannot find module '@rpgjs/c
ommon' or its corresponding type declarations.
[watch:client] src/RpgClient.ts(2,28): error TS2307: Cannot find module '@rpgjs/
common' or its corresponding type declarations.
[watch:client] src/RpgClientEngine.ts(6,23): error TS2307: Cannot find module '@
rpgjs/sync-client' or its corresponding type declarations.
[watch:client] src/RpgClientEngine.ts(16,8): error TS2307: Cannot find module '@
rpgjs/common' or its corresponding type declarations.
[watch:client] src/Scene/Battle.ts(1,32): error TS2307: Cannot find module '@rpg
js/common' or its corresponding type declarations.
[watch:client] src/Scene/Map.ts(1,53): error TS2307: Cannot find module '@rpgjs/
common' or its corresponding type declarations.
[watch:client] src/Scene/Scene.ts(1,39): error TS2307: Cannot find module '@rpgj
s/common' or its corresponding type declarations.
[watch:client] src/Sprite/Character.ts(1,34): error TS2307: Cannot find module '
@rpgjs/common' or its corresponding type declarations.
[watch:client] src/Tilemap/index.ts(1,23): error TS2307: Cannot find module '@rp
gjs/common' or its corresponding type declarations.

**Comment by RSamaium** [comment]
Hello,

If you install the repository in development mode, do you have these steps?

```
git clone https://github.com/RSamaium/RPG-JS.git
npm install
npm run dev
```

If not, can you indicate when the problem occurs? (command line?)

Thanks

**Comment by cryptonft** [comment]
followed the above commands (adding in cd RPG-JS):
> lerna bootstrap && npm run build:common && npm run build:sync-client && npm run build:sync-server && npm run build:client && npm run build:database && npm run build:server && npm run build:testing

lerna notice cli v4.0.0
lerna info Bootstrapping 25 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@rpgjs/title-screen'
lerna ERR! npm install stderr:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @rpgjs/client@3.0.0-beta.1.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2021-12-08T20_09_24_485Z-debug.log
lerna ERR! npm install exited 1 in '@rpgjs/title-screen'
lerna WARN complete Waiting for 7 child processes to exit. CTRL-C to exit immediately.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rpgjs@3.0.0-beta postinstall: `lerna bootstrap && npm run build:common && npm run build:sync-client && npm run build:sync-server && npm run build:client 
&& npm run build:database && npm run build:server && npm run build:testing`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rpgjs@3.0.0-beta postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2021-12-08T20_09_25_006Z-debug.log

**Comment by cryptonft** [comment]
Specifically within the log:

34864 warn @rpgjs/compiler@3.0.0-beta.1 No description
34865 warn @rpgjs/compiler@3.0.0-beta.1 No repository field.
34866 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
34867 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
34868 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
34868 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
34868 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
34868 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
34869 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
34870 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
34871 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
34871 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
34871 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
34871 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
34872 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\chokidar\node_modules\fsevents):
34873 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
34874 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
34874 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
34874 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
34874 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
34875 verbose stack Error: deasync@0.1.21 install: `node ./build.js`
34875 verbose stack Exit status 1
34875 verbose stack     at EventEmitter.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
34875 verbose stack     at EventEmitter.emit (node:events:394:28)
34875 verbose stack     at ChildProcess.<anonymous> (C:\Users\xxx\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
34875 verbose stack     at ChildProcess.emit (node:events:394:28)
34875 verbose stack     at maybeClose (node:internal/child_process:1064:16)
34875 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
34876 verbose pkgid deasync@0.1.21
34877 verbose cwd D:\xxx\RPG-JS\packages\compiler
34878 verbose Windows_NT 10.0.19042
34879 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
34880 verbose node v16.8.0
34881 verbose npm  v6.14.15
34882 error code ELIFECYCLE
34883 error errno 1
34884 error deasync@0.1.21 install: `node ./build.js`
34884 error Exit status 1
34885 error Failed at the deasync@0.1.21 install script.
34885 error This is probably not a problem with npm. There is likely additional logging output above.
34886 verbose exit [ 1, true ]

**Comment by cryptonft** [comment]
got it working again on node v10.x
not sure if this is to do with some dependent called ...sass being limited to node 10.x-11

**Comment by cryptonft** [comment]
Ok. on reinstall it failed again. I think it relates to the Lerna package problem in the other open issue.

**Comment by cryptonft** [comment]
Sort of solved by npm remove lerna + npm install lerna

**Comment by RSamaium** [comment]
Currently, RPGJS is limited to NodeJS 14 (because of SASS)
