### ISSUE TITLE
Black chunks for maps of different size?

### ISSUE THREAD

**Issue by cryptonft** [RSamaium/RPG-JS#113]
I tried making modifications to the rpgjs/starterkit which had some blacked out sections relating to the demo map despite completely removing its layers and putting in my own. 

![image](https://user-images.githubusercontent.com/80640570/147863809-dd10e289-a1e8-4417-a55a-37f894cbb6fa.png)

**Comment by cryptonft** [comment]
Previous version before latest update.

**Comment by cryptonft** [comment]
Still happening in latest version. Not sure if there is a size limit variable somewhere that I am not tweaking. I have taken a screenshot of where it's happening to the "cave" map when I expand from 20x20 tile to 200x200 tile

![image](https://user-images.githubusercontent.com/80640570/148224634-e504357c-adac-4dbb-81e8-6e34e2332efb.png)

**Comment by cryptonft** [comment]
Not sure if its a capacity issue... when I transform trees/plants into objects instead of tiles, it crashes super quick in addition to the black outs. 

Does RPGJS have chunking?

**Comment by RSamaium** [comment]
The maps are based on https://github.com/pixijs/tilemap and are optimised even with a lot of tiles (this is not the case with objects)

And (PIXI Tilemap source):

> There's also a limitation on 16k tiles per one tilemap.

So, indeed, 200x200 is too big. It is possible to solve the problem by modifying `use32bitIndex` in the framework (it is up to me to add this possibility)

Ideally, there should be a chunk system, not present in the current version.
It is always advisable to have smaller maps, especially for MMORPG mode :)
