### ISSUE TITLE
How to mass scale object interaction?

### ISSUE THREAD

**Issue by cryptonft** [RSamaium/RPG-JS#117]
Do I need to create a "chop" event for 100+ trees I have on the map? If there are any resource gathering skills, how would you go about that? I tried generating 100+ trees on Tiled maps and created a single event similar to the chest event, but it didn't seem to scale. 

The demo seems to only allow for 1 of 1 interactions to be manually typed.

Also, could the +gold be duplicated into +wood? and +exp to +woodcuting_xp?

**Comment by RSamaium** [comment]
Hello,

Thank you for your questions.

Your questions will interest other people, but on Github, the issues are rather thought for feedback on the source code (bug, etc.)

I have now opened a discussion forum that will be rather appropriate for help:

https://community.rpgjs.dev

Can you repost your request on the forum? I'll be happy to answer afterwards (with an example code)

Thanks

**Comment by cryptonft** [comment]
Will do thank you!
