### ISSUE TITLE
Menu button & action button not working in latest update?

### ISSUE THREAD

**Issue by cryptonft** [RSamaium/RPG-JS#138]
Not sure if its just me, but the two on-screen buttons ( Menu + A) don't seem to be working for me since the last update. Will alsoo pose a question in the forums on keyboard alternatives.

**Comment by RSamaium** [comment]
Thanks for the feedback, I'll check it out and get back to you

**Comment by RSamaium** [comment]
I have no particular concerns after a few tests on my side. 
Do you have an error in the browser console?

In `src/modules/main/server/player.ts`:

```ts
import { RpgPlayer, RpgPlayerHooks } from '@rpgjs/server'

export const player: RpgPlayerHooks = {
    onInput(player: RpgPlayer, { input }) {
        console.log(input)
    }
}
```
Do you receive the input value?

**Comment by cryptonft** [comment]
Ye, I have tried both desktop chrome browser and mobile. I will check the above and if it doesn't work, will try another clean install again.

**Comment by cryptonft** [comment]
I have tried adding the console.log input - it does not seem to be triggered as it does not log anything. 

No memu's are working, but the gameplay keys are working (arrows, space, enter to interact).

**Comment by cryptonft** [comment]
Ok. Finally found the bug. The bug is with Mobile-GUI, potentially with the combination of the Chat module. 

When I recently added MongoDB to the game to make it MMORPG, I couldn't click Login/Create Account / Menu button / Action button, nor select the textboxes. 

Upon removing the import mobileGui from '@rpgjs/mobile-gui', I could click the buttons. However, this does mean a lot of the in game texts / popup boxes are gone, along with the menu/action buttons.

**Comment by RSamaium** [comment]
Ok, I see the problem then, it's the div of the Mobile-GUI module that must be on top of the other menus preventing some interactions.

I'll try to reproduce it and correct this problem

**Comment by RSamaium** [comment]
Hello,

The Mobile-GUI module is displayed if a map is loaded. Make sure you are not loading a map at the same time as the title screen is loading

https://community.rpgjs.dev/d/49-auth-mongodb-handle

**Comment by cryptonft** [comment]
A new error from the v3 update - from running npm run dev

[sample] TypeError: Cannot read property 'close' of undefined
[sample]     at Object.<anonymous> (D:\RPG-JS-3\packages\compiler\node_modules\chalk\index.js:72:75)
[sample]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[sample]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[sample]     at Module.load (internal/modules/cjs/loader.js:950:32)
[sample]     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
[sample]     at Module.require (internal/modules/cjs/loader.js:974:19)
[sample]     at require (internal/modules/cjs/helpers.js:93:18)
[sample]     at Object.<anonymous> (D:\RPG-JS-3\packages\compiler\node_modules\postcss\lib\css-syntax-error.js:8:37)
[sample]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[sample]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[sample] npm ERR! code ELIFECYCLE

**Comment by RSamaium** [comment]
You can try with the latest version (3.0.0-beta.8). I don't have any problem on my side, it must come from dependencies problems in the compiler

**Comment by cryptonft** [comment]
New issues, not sure if at all related to the dependency problems:

> node bin/postinstall || exit 0

npm WARN my-game@3.0.0-beta No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\watchpack-chokidar2\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})


Not sure why the slash/backslash is mixed below. 


(node:13284) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, mkdir 'D:\my-game/dist/server/maps'
    at Object.mkdirSync (fs.js:987:3)
    at Object.worldLoader (D:\JX\NFT-721\MetaMapsApr2\node_modules\@rpgjs\compiler\tmx-loader\world-loader.js:16:12)
    at LOADER_EXECUTION (D:\JX\NFT-721\MetaMapsApr2\node_modules\loader-runner\lib\LoaderRunner.js:119:14)
    at runSyncOrAsync (D:\JX\NFT-721\MetaMapsApr2\node_modules\loader-runner\lib\LoaderRunner.js:120:4)
    at iterateNormalLoaders (D:\JX\NFT-721\MetaMapsApr2\node_modules\loader-runner\lib\LoaderRunner.js:232:2)
    at Array.<anonymous> (D:\JX\NFT-721\MetaMapsApr2\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\JX\NFT-721\MetaMapsApr2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\JX\NFT-721\MetaMapsApr2\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9
    at D:\JX\NFT-721\MetaMapsApr2\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:13284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by RSamaium** [comment]
Indeed, I have updated the compiler. You can update to the version:

`npm i @rpgjs/compiler@3.0.0-beta.8.0.1`
