### ISSUE TITLE
CharaEvent - onCollision

### ISSUE THREAD

**Issue by sandrocantagallo** [RSamaium/RPG-JS#140]
Is possible to track or start event when player simple "touch" CharaEvent?

Like Start a combat ? Or simple talk to it?

**Comment by RSamaium** [comment]
Hello,

Do you want to trigger _another_ event? Or do you want to keep the current event in memory?

PS: If you need help on the framework, [feel free to use the forum](https://community.rpgjs.dev) ;)

**Comment by sandrocantagallo** [comment]
Hy, I would like to create an NPC that walk randomic into map. When player touch it (just touch don't press any button) an event start.

in documentation: https://docs.rpgjs.dev/guide/create-event.html#it-is-necessary-to-know

I see online:

```JAVASCRIPT
 onInit(player: RpgPlayer) {
    }

    onAction(player: RpgPlayer) {
       // here, the controls on the player
    }
```

exist something like "onCollision". ?

**Comment by RSamaium** [comment]
Yes, you have `onPlayerTouch()`: https://docs.rpgjs.dev/classes/event.html#onplayertouch

Then you can set up another event that has the `onChanges()` hook and as soon as a variable on the player is activated, this event will have the behavior you want

https://docs.rpgjs.dev/classes/event.html#onchanges
