### ISSUE TITLE
16x16 pixel map doesn't work with rpgjs

### ISSUE THREAD

**Issue by kfdl** [RSamaium/RPG-JS#148]
Hello, 

I have an issue while creating a map with the tile size : 16x16 pixel,
the map is black, but when I change the tile size to 32x32 everything is ok, 

Can you give me a tips about this issue? 
thank you

very good work btw 👍

**Comment by RSamaium** [comment]
Indeed, I just tried and it doesn't work. I'll fix it

Thanks

Edit: it actually works

**Comment by kfdl** [comment]
Thanks for your support can't wait until the fix :)

**Comment by RSamaium** [comment]
Correction, it works very well.

Make sure you have added the tileset on the client side (which I had forgotten on my side)

**Comment by kfdl** [comment]
Ok I gonna test again I will let you know

**Comment by kfdl** [comment]
I have already add the Tiletset to the client side 

import { Spritesheet } from '@rpgjs/client'

@Spritesheet({
    images: {
        ninjafloor: require('./assets/TilesetFloor.png'),
        ninjanature: require('./assets/TilesetNature.png')
        // here, you can add other tileset
    }
})
export class Tilesets { }

And it still not working
I have follow the process in the documentations:
https://docs.rpgjs.dev/guide/get-started.html

And I use this bundle of Tileset:
https://pixel-boy.itch.io/ninja-adventure-asset-pack

That is weird is still not working I probably miss something

**Comment by RSamaium** [comment]
Try

```ts
@spritesheet({
    images: {
        TilesetFloor: require('./assets/TilesetFloor.png'),
        TilesetNature: require('./assets/TilesetNature.png')
    }
})
```

The key must be the same as the image name so that Tiled Map Editor can find the tileset

**Comment by kfdl** [comment]
ok it's work now I did the same for the name of the tsx file and the name of the tileset **in** the txs they must be the same.

Thank for the quick support :)

**Comment by RSamaium** [comment]
I will add this point in the documentation, it is not clear.
But I am improving the compiler so that it can take the tileset directly without having to declare it in the Typescript :)

**Comment by kfdl** [comment]
Can't wait 😃
