### ISSUE TITLE
Error: Cannot find module 'browser-sync-client/dist/index.min.js'

### ISSUE THREAD

**Issue by LehaoLin** [RSamaium/RPG-JS#153]
`Error: Cannot find module 'browser-sync-client/dist/index.min.js'`
The error shows after running `RPG_TYPE=rpg npm run dev`

**Comment by RSamaium** [comment]
Thanks for the feedback. There is indeed a problem on the compilation of the RPG mode. I will make a correction tomorrow

**Comment by LehaoLin** [comment]
Hi @RSamaium, I recommend you to use Vite https://vitejs.dev/ instead of Webpack to do the compilation, which is faster and can save a lot of time when dev.
I think the settings could be easy and you can try it if you have spare time.
Hope it can help this project.

**Comment by RSamaium** [comment]
Yes, I know vitejs. However, it requires to review all the development of the compiler...

Thanks for the tip

**Comment by RSamaium** [comment]
Update with:

`npm i @rpgjs/server@3.0.0-beta.9.2 @rpgjs/standalone@3.0.0-beta.9.1 @rpgjs/compiler@3.0.0-beta.9.1`

**Comment by LehaoLin** [comment]
Many thanks! 
I re-install packages and it works!
