### ISSUE TITLE
`npx digit rpgjs/starter xxx` didn't work

### ISSUE THREAD

**Issue by onion108** [RSamaium/RPG-JS#158]
I'm trying to run `npx digit rpgjs/starter xxx`, but I can't find a directory called `xxx` in my working directory. It just ended silently, and without any error or warnings or something similar. It really confused me.  
  
About the system info, I'm using the macOS 12.4 with npm 8.1.2 and node 16.13.1

**Comment by RSamaium** [comment]
Strange, I think the problem is on the `degit` module 

Try to clone the repo

`git clone https://github.com/rpgjs/starter`

> RPGJS works only on NodeJS v14
