### ISSUE TITLE
Add global Settings to control movement speed instead of FPS

### ISSUE THREAD

**Issue by mqllin** [RSamaium/RPG-JS#178]
I ran dev demo on three computers.there are each with 60hz(old laptop),120Hz(Macbook Promition) and 240Hz(PC).It only looks right on a 60Hz old laptop.
On my 240Hz Pc,So fast I can barely control it!
[I reported too there](https://community.rpgjs.dev/d/81-limit-canvas-refresh-rate/2)

**Comment by RSamaium** [comment]
Duplicate #176

**Comment by RSamaium** [comment]
The problem has been fixed on the latest release (version 3.0.3 of @rpgjs/client)

You can update: `npm update`
