### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [RSamaium/RPG-JS#182]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by RSamaium** [comment]
Hello,

Yes, of course. What makes you think that the project is not active? :smile:

**Comment by ghost** [comment]
Hi RSamaium.

> Hello,
> Yes, of course. What makes you think that the project is not active? smile

thank you for feedback... so... I'm new to this repository, and I don't know how it works, so I asked something initial.

**Comment by RSamaium** [comment]
No worries! If you have any questions, either on Github or on https://community.rpgjs.dev

Have a nice day

**Comment by ghost** [comment]
Hi RSamaium.

> No worries! If you have any questions, either on Github or on https://community.rpgjs.dev/
> Have a nice day

thank you for feedback again.
