### ISSUE TITLE
onInput() does not accept any GUI related "player" methods

### ISSUE THREAD

**Issue by designdegenerate** [RSamaium/RPG-JS#184]
I followed the instructions in the README for initializing a new game. The only extra addition I added was changing the npm run dev command from ``rpgjs dev`` to ``RPG_TYPE=rpg rpgjs dev`` in package.json.

Upon playing the sample game, hitting "esc" should open the menu. Instead a "player.callMenu is not a function" is returned in the console from modules/main/player.ts. Doing a quick ``console.log(player)`` on the onJoinMap() and onInput() properties in that same file reveals that the player object from onJoinMap() is a proxy, whereas onInput() returns RPGCommonPlayer directly.

I can share any additional details if needed.

Edit: Also, my IDE (vscode) gives no errors on the callMenu method, only the browser does. showText also does not work, and presumably all the methods that come from the default-gui package.

My System:
macOS 13.1 (Chrome 109.0.5414.119, also present on Firefox 109.4)
Node v14.21.2 (npm 6.14.17) (using the nvm version manager)

Thanks!

**Comment by RSamaium** [comment]
Hello,

Thanks for the feedback. It will be corrected.
