### ISSUE TITLE
swap nodejs server for Rust server ?

### ISSUE THREAD

**Issue by zeroexcuses** [RSamaium/RPG-JS#185]
Hi,

  I am interested in understanding how much work would be involved in rewriting the nodejs server in Rust. Only the server part. The client stays unchanged. I am looking for advice on approximately that this entails.
```
packages/server]$ cloc lib/ src/
     168 text files.
     126 unique files.                                          
      42 files ignored.

github.com/AlDanial/cloc v 1.94  T=0.08 s (1571.2 files/s, 209110.4 lines/s)
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
TypeScript                      84            498           6203           4480
JavaScript                      42              2           2476           3110
-------------------------------------------------------------------------------
SUM:                           126            500           8679           7590
-------------------------------------------------------------------------------
```
looks doable ; but I am wondering about other things to be aware of.

Thanks!

**Comment by RSamaium** [comment]
Hello,

You can try to write a Rust server but a major idea of RPGJS is to have common files (https://github.com/RSamaium/RPG-JS/tree/v3/packages/common) in the same language.

I don't see the extent of the work in Rust as I don't know much about this language
