### ISSUE TITLE
Error: Cannot find module '.../dev'

### ISSUE THREAD

**Issue by coffeeAdd1ct** [RSamaium/RPG-JS#187]
Hi, I am trying to install the package to begin development, but when I go to run the server(npm/nvm run dev), the output is telling me that 'Cannot find module '/Users/kev/Dev/tcd/dev'. It seems like the module was not installed correctly? But I've run the installation several times now with this repeated effect. 

![Screenshot 2023-03-18 at 9 17 36 AM](https://user-images.githubusercontent.com/47570939/226114771-c6da9029-9b6b-45d9-a3ba-f8617c54986f.png)

Please help me figure this out as this library looks awesome and I'd love to be a part of the community using and improving! I'm on a Mac M2 chip, fwiw, which is why I'm using nvm

**Comment by RSamaium** [comment]
Hello,

And if you use `npm` instead of `nvm` ?

`npm run dev`

**Comment by coffeeAdd1ct** [comment]
<img width="695" alt="image" src="https://user-images.githubusercontent.com/47570939/226194744-c2c29d1d-22d6-4c63-b1a9-885c0183811e.png">

**Comment by RSamaium** [comment]
did you install the nodejs dependencies before ?

`npm install`

**Comment by coffeeAdd1ct** [comment]
I had to use nvm to install `node -v 14.21.3`

**Comment by RSamaium** [comment]
The error indicates that the `node_modules` folder does not exist. You must do `npm install` before `npm run dev`

**Comment by coffeeAdd1ct** [comment]
Oh I see, I had to use nvm to run node, then npm to start the dev server
<img width="268" alt="image" src="https://user-images.githubusercontent.com/47570939/226204104-c39ae7d4-f141-4efb-b86d-cf7db28c8bb0.png">
<img width="461" alt="image" src="https://user-images.githubusercontent.com/47570939/226204185-03bab9f6-9b80-47f4-8cf0-16739ec0ef28.png">

My game is loading a black screen, though that may be the expectation on a new project. Thank you for the assistance, I really appreciate your time and this library.
