### ISSUE TITLE
Can't use item

### ISSUE THREAD

**Issue by dominx99** [RSamaium/RPG-JS#195]
I think it can be related to: https://github.com/RSamaium/RPG-JS/issues/146

I installed version 4 by
```
npx degit rpgjs/starter#v4 my-rpg-game
cd my-rpg-game
npm install
npm run dev # and go to localhost:3000
```

I added `main/database/items/Potion.ts`

```
import { Item } from '@rpgjs/database'

@Item({
    id: 'potion',
    name: 'Potion',
    description: 'Gives 100 HP',
    price: 200,
    hpValue: 100,
    hitRate: 1,
    consumable: true,
    addStates: [],
    removeStates: [],
    elements: [],
    paramsModifier: {}
})
export default class Potion {}
```

Then when I click on this item I am getting: `caught TypeError: this.rpgSocket.emit is not a function`

![image](https://github.com/RSamaium/RPG-JS/assets/25711467/31a43e89-3f05-4899-9c34-69e1a038152d)

**Comment by RSamaium** [comment]
Hello,

Thanks for the feedback. I can see the problem, it will be fixed soon.

**Comment by dominx99** [comment]
Hello @RSamaium  I saw you fixed that and many others. Could you please release this as a new beta tag?
Or maybe there is a possibility to always `npm update` from the latest `v4` branch? Because I failed trying to achieve that

**Comment by RSamaium** [comment]
You can update to the latest version
