### ISSUE TITLE
Can't assign D input to the action

### ISSUE THREAD

**Issue by dominx99** [RSamaium/RPG-JS#196]
I installed version 4

and added to `rpg.toml`  this:

```
[inputs.up]
    name = "up"
    repeat = true
    bind = "w"

[inputs.down]
    name = "down"
    repeat = true
    bind = "s"

[inputs.right]
    name = "right"
    repeat = true
    bind = "d"

[inputs.left]
    name = "left"
    repeat = true
    bind = "a"
```

My hero does not move right direction (D is not assignable)

Expected result: My player can move to right direction

**Comment by RSamaium** [comment]
Hello,

I can't reproduce the error. On my side, the character moves well.

I'm still looking...

**Comment by dominx99** [comment]
Hello,

You were right.
I am sorry, this issue occurred because of my browser extension.
