### ISSUE TITLE
Error - Demo not loading in homepage - 404

### ISSUE THREAD

**Issue by psociety** [RSamaium/RPG-JS#198]
https://rpgjs.dev/ -> https://demo.rpgjs.dev
`404 page not found`

By the way, i saw some references to isometric tiles on tiled package. Does that mean the RPG JS supports isometric maps?

**Comment by RSamaium** [comment]
Hello,

Thanks for the feedback. The demo is currently switched off. I'll put it back on soon.

> By the way, i saw some references to isometric tiles on tiled package. Does that mean the RPG JS supports isometric maps?

No, no isometric support ;)
