### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'tileWidth')

### ISSUE THREAD

**Issue by dominx99** [RSamaium/RPG-JS#209]
This issue from the title happens often in the console.

```
TypeError: Cannot read properties of undefined (reading 'tileWidth')

  - MoveManager.ts:80
    [v4]/[@rpgjs]/server/src/Player/MoveManager.ts:80:46

  - MoveManager.ts:142
    [v4]/[@rpgjs]/server/src/Player/MoveManager.ts:142:24

  - MoveManager.ts:447
    [v4]/[@rpgjs]/server/src/Player/MoveManager.ts:447:28

  - Array.map

  - MoveManager.ts:445
    [v4]/[@rpgjs]/server/src/Player/MoveManager.ts:445:29

  - new Promise

  - MoveManager.ts:443 Proxy.moveRoutes
    [v4]/[@rpgjs]/server/src/Player/MoveManager.ts:443:16

  - MoveManager.ts:540 move
    [v4]/[@rpgjs]/server/src/Player/MoveManager.ts:540:18

  - MoveManager.ts:543 Proxy.infiniteMoveRoute
    [v4]/[@rpgjs]/server/src/Player/MoveManager.ts:543:9

  - FollowManager.ts:92 Function.moveRandomly
    /workspace/rpg/v4/main/battle/FollowManager.ts:92:16
```

I spotted today a single situation that triggers this exception.

For context:
I have a mechanism that after the event is attacked by the player the event follows the player (`moveTo`)
Then when I change map => `onLeaveMap` I trigger 
```
        victim.stopMoveTo();
        victim.breakRoutes(true);
        victim.infiniteMoveRoute([
            Move.tileRandom()
        ]);
```
on all events that are following the player and then this issue occurs.
In my opinion, it tries somehow to get the `tileWidth` of an event that is not anymore loaded. because I changed the map to another one and none players are still on the map that event tries to move randomly?

I assume that this is a correct assumption because when I set up two players (2 incognito browsers) and one of them changes the map then the issue does not occur in the server console.

The next thing I tried was to remove all events on the map when there are no more players on the map by:
```

    onLeave(player: RpgPlayer): void {
        if (this.nbPlayers > 0) {
            return;
        }

        Object.entries(this.events || [])
            .filter(([eventId, event]) => event instanceof KillableMob)
            .forEach(([eventId, event]) => {
                this.removeEvent(eventId);
            })
        ;
    }
```
And it helped! But then I am getting this in browser (client) console:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'complete')
    at _GameEngineClient.resetObjects (GameEngine.ts:125:34)
    at Object.next (RpgClientEngine.ts:523:37)
    at ConsumerObserver2.next (Subscriber.ts:161:25)
    at Subscriber2._next (Subscriber.ts:119:22)
    at Subscriber2.next (Subscriber.ts:75:12)
    at Subject.ts:68:20
    at errorContext (errorContext.ts:29:5)
    at Subject2.next (Subject.ts:61:5)
    at BehaviorSubject2.next (BehaviorSubject.ts:37:15)
    at Socket2.<anonymous> (world.ts:96:23)
```

Also there is black screen with loading in both cases.

**Comment by dominx99** [comment]
Ok, I see why adding `onLeave` solves the issue from the title and generates another one.

```
    // Hook: called by simple-room package
    onLeave(player: RpgPlayer) {
        this.removeObject(player)
    }
```

When I override this hook then the player is not removed from the map.
Also I cannot call removeObject because it is private, so in my opinion `onLeave` should be `@internal`

**Comment by RSamaium** [comment]
Thanks for the feedback, I'm looking into it

**Comment by RSamaium** [comment]
This has been corrected in the latest version. I had trouble reproducing the problem, but I was able to identify it.

> The next thing I tried was to remove all events on the map when there are no more players on the map by

In the engine, when there are more players on the map, the map and all its events are removed from the cache.

**Comment by dominx99** [comment]
I confirm that the exception from the title does not occur anymore while changing the map.
