### ISSUE TITLE
Uncaught (in promise) TypeError: resource is not a constructor (v4)

### ISSUE THREAD

**Issue by FaustinM** [RSamaium/RPG-JS#210]
When I try to add a music in the same way of the official guide, the game never load.
```Uncaught (in promise) TypeError: resource is not a constructor```
Thanks!
Faustin

**Comment by RSamaium** [comment]
Thanks for the feedback, it's been corrected in the latest version.

**Comment by FaustinM** [comment]
Thanks for your time as maintainer!
