### ISSUE TITLE
Integration with nuxt possible?

### ISSUE THREAD

**Issue by Q16solver** [RSamaium/RPG-JS#268]
Hello! I was looking at the docs for rpgjs and it’s very amazing that it incorporates being able to use vue as the GUI. However, I’m currently using nuxt and I wanted to see if I can use rpgjs to make a small rpg game in a route like in website/rpg. It seems like the directory structure for rpgjs is set, and it uses express as the server. It also defaults to mongodb for auth I think? I wanted to use nuxt as the server + pinia as my central state management tool with this and also my auth depends on Postgres so I wanted to ask if there was some flexibility in defining my own functions to pass to rpgjs for that, kind of like an adapter and also defining the paths for the rpgjs compiler to detect

**Comment by RSamaium** [comment]
Hello,

There are currently no tests with Nuxt. I can't really comment on it.

You should know that Vue instance is created directly in the RPGJS engine to then display user interfaces on top of the game. This instance can be retrieved via the API

As for the database, you're free to use whatever you like in RPGJS. MongoDB is only used for a plugin to connect to the game.
