### ISSUE TITLE
Passable tiles

### ISSUE THREAD

**Issue by gamemasterx** [RSamaium/RPG-JS#46]
For the passability of the tiles, there is used a hex value. On the website I read that 15 means that the tile is passable, but it's not. That's with zero. But for all the other numbers than zero, my tile is not passable at all the sides. I have to create tiles which are passable at by example 2 of the 4 sides, but is this still possible?

**Comment by RSamaium** [comment]
Version 2 being obsolete. I close the ticket.

Feel free to use version 3. Thank you!
