### ISSUE TITLE
RPG maker xp

### ISSUE THREAD

**Issue by Gunzmo** [RSamaium/RPG-JS#49]
Hi i used the script to export the maps from RPG Maker xp but when i load the map on RPGJS its just a white map with no titleset or anything is the script i used is this one:
https://github.com/RSamaium/RPG-JS/tree/old/rmxp
any new scripts or is it just need to be renew'd

**Comment by RSamaium** [comment]
Version 2 being obsolete. I close the ticket.

Feel free to use version 3. Thank you!
