### ISSUE TITLE
Main page example is not working

### ISSUE THREAD

**Issue by Jastkast** [RSamaium/RPG-JS#51]
Uncaught TypeError: undefined is not a function
canvasengine-latest.all.min.js:21
Input.Input.Gamepad.getState canvasengine-latest.all.min.js:21
Input.Input.Gamepad.update canvasengine-latest.all.min.js:21
RPGJS_Canvas.Scene.New.render Scene_Map.js:249
Class.create._loop canvasengine-latest.all.min.js:11
e canvasengine-latest.all.min.js:11

Chrome 35.0.1916.114

**Comment by RSamaium** [comment]
Version 2 being obsolete. I close the ticket.

Feel free to use version 3. Thank you!
