### ISSUE TITLE
Bower Package Missing

### ISSUE THREAD

**Issue by schmijos** [RSamaium/RPG-JS#54]
I didn't find any bower packages of your project. Is there any reason for that?

**Comment by neemzy** [comment]
IMHO, that's not quite the type of library you can expect to find on Bower. However, the project not being published and not having a `bower.json` file doesn't stop you from using it:

```
bower install git@github.com:RSamaium/CanvasEngine.git --save-dev
bower install git@github.com:RSamaium/RPG-JS.git --save-dev
```

In your HTML file:

```
<script src="bower_components/CanvasEngine/canvasengine-1.3.2.all.min.js"></script>
<script src="bower_components/RPG-JS/rpgjs-2.0.0.min.js"></script>
```

**Comment by schmijos** [comment]
Aight, thank you very much.
