### ISSUE TITLE
ARPG plugins example

### ISSUE THREAD

**Issue by sandrocantagallo** [RSamaium/RPG-JS#56]
Can you please POST a simple example with ARPG at work ? Just a mob to kill for understand how do that.

Thanks a lot.

**Comment by sandrocantagallo** [comment]
ok i found the way:

modiy database.json including extra data from actors and actions (not present in default)

`"actors": {
        "1": {
            "name": "Sandro",
            "level_min": "1",
            "level_max": "99",
            "class": "2",
            "graphic": "1",
            "graphic-params":{
					            "direction":"up",
					            "pattern":"0",
					            "nbSequenceX":"4",
					            "nbSequenceY":"4",
					            "regX":"0",
					            "regY":"0"
					            
					            
					            },
            "weapon": "2",
            "shield": "2",
            "helmet": "4",
            "body_armor": "0",
            "accessory": "0",
            "params": {}
        }`

` "actions": {
					"2": {
						"name": "Mazzata",
						"keypress": "A",
						"id_for_plugin": "arpg",
						"hitbox": {
							"left": [-40, 0, 40, 48],
							"right": [32, 0, 40, 48],
							"up": [0, -40, 32, 40],
							"bottom": [0, 48, 32, 40]
						},
						"graphic": "1",
						"graphic-params": {
							"uniqid": 1465297510800,
							"path": "/Graphics/Characters/2.png"
						},
						"speed": "2",
						"id": 2
					}
	},`

than in the map when you want spawn mob you must add dynamic_event for example in map 1:

`"dynamic_event": [{
								"x"		: "11",
								"y"		: "14",
								"name"	: "enemies",
								"id"	: "2"
							}]`

there are no documentation about it and found the right way make my insane!! please add documentation on arpg and in sample a little file with dimostration and update database.json with a simple action and a mob to try fight.

**Comment by RSamaium** [comment]
Version 2 being obsolete. I close the ticket.

Feel free to use version 3. Thank you!
