### ISSUE TITLE
Scene_Menu.js - Button on left unable to work

### ISSUE THREAD

**Issue by sandrocantagallo** [RSamaium/RPG-JS#57]
![screenshot 357](https://cloud.githubusercontent.com/assets/9352423/15859685/6fa12c38-2cc6-11e6-8add-7de10516ad50.png)

i'm not able to understand how to activate button on the left. i can move with arrow and select button but with enter key nothing will do. how it work ?

**Comment by sandrocantagallo** [comment]
there is a BUG in Scene_Menu.js in __index function line: 161
sprite button element don't have width and height declarated and for this reason: box.cursor.select
don't work right.

for fix it change:

`sprite_b = this.createElement();`

with:

`sprite_b = this.createElement(300, 70);`

the script is full of BUG:

for example if you save game. there is no way for exit from save windows (ESC button don't work remove saved box but index don't show).

**Comment by sandrocantagallo** [comment]
ok find a way to exit from save menu in game. This mod work only with a Load_Scene.js modify (see issues open).

`__save: function(stage) {
		console.log("apro lo scenario save");
		var scene = RPGJS.scene.call("Scene_Load", {
			overlay: true
		});
		scene.refresh("save");
		this._esc(function() {
			console.log("Chiamata esc della funzione save in Scene_Menu");
			Marshal._pointer["rpg_slot1"] = 0;
			RPGJS_Canvas.Scene.exit("Scene_Load");
			RPGJS_Canvas.Scene.exit("Scene_Menu");
		});
	},`

**Comment by RSamaium** [comment]
Version 2 being obsolete. I close the ticket.

Feel free to use version 3. Thank you!
