### ISSUE TITLE
Scene_Load.js - Problem in the save game system

### ISSUE THREAD

**Issue by sandrocantagallo** [RSamaium/RPG-JS#58]
There are some bugs:

1- If you save a game and refresh the browser in title page click on load you can see the saved game but if you go back in title menu and return on load page you see undefined and na/na in the box.
![screenshot 360](https://cloud.githubusercontent.com/assets/9352423/15930470/7234e410-2e53-11e6-9510-1964f3ab0b15.png)

2- if you load a game and in game click ESC and in the menu click on SAVE script blocking to  work.

3- Marshal.js is not able to use five saved slot...or there are some bug in the use of class becouse during the data reading Marshal class lost the right pointer and is unable to reload saved data.

Possible fast solution:
reduce to 1 slot the saved system:

on ready function of Scene.Load.js

`for (var i=0 ; i < 1 ; i++) {`

than in refresh function modify:

`//RPGJS.scene.call("Scene_Title");
                location.reload();`
in this way when go back in title menu you reload page and the page don't broke

than in execLoad 

`_execLoad: function(el, data_save) {

```
    console.log("sto caricando una partita avente slot: " + el.attr('name'));
    console.log(data_save);
    var slot = el.attr('name');

    if (!el.attr('exist')) {
        return;
    }

    global.game_save = data_save;
    //global.game_save = Class.New("Game_Save");
    global.game_switches = Marshal.load(slot);
    global.game_variables = Marshal.load(slot);
    global.game_selfswitches = Marshal.load(slot);
    global.game_actors = Marshal.load(slot);
    global.game_player = global.game_actors.get(0);

    global.game_player.x /= global.game_map.tile_w;
    global.game_player.y /= global.game_map.tile_h;
    /* resetto il puntatore altrimenti mi va in errore la funzione di caricamento */
    Marshal._pointer[slot] = 0;
    //Marshal.remove(slot);
    RPGJS.scene.call("Scene_Map", {
        params: {
            map_id: global.game_player.map_id
        }
    }).load();
},
`
```

manualy reset the MArshal pointer for make it work.

in game i do know how exit from save scene. If you click exit box fade out but background persist.

**Comment by RSamaium** [comment]
Version 2 being obsolete. I close the ticket.

Feel free to use version 3. Thank you!
