### ISSUE TITLE
pre-built gui controls not displayed by default on the demo website or starter-kit

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#82]
Go to https://rpgjs.dev, https://demo.rpgjs.dev/ or execute

    npx degit rpgjs/template my-rpg-game
    cd my-rpg-game
    npm install
    npm run dev

By default the menu and "A" button don't show up, nor the nipplejs joystick. However, if you press "Escape" to enter the menu and "Escape" again to exit, they do. Currently this makes the demo unusable on mobile.

A fix is either to call `RpgGui.display(PrebuiltGui.Controls)` on the client side (as in https://docs.rpgjs.dev/guide/responsive-design.html#controls) or `this.gui('rpg-controls').open()` on the server side (as in https://docs.rpgjs.dev/guide/create-gui.html#server-side).

**Comment by RSamaium** [comment]
Hello,

Thank you very much for the feedback. I'll look at it very soon and add the corrections

**Comment by fred-wang** [comment]
> Hello,
> 
> Thank you very much for the feedback. I'll look at it very soon and add the corrections

Hi I think #83 is the biggest issue for my use case, the other ones I don't need them to be fixed or can easily work around the bug. Thanks for writing RPG-JS BTW!

**Comment by RSamaium** [comment]
Changes have been made to the `dev` branch, I'll let you know when it's released

**Comment by RSamaium** [comment]
Fixed on the update (alpha.10)
