### ISSUE TITLE
showChoices can block the player control after exit

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#84]
1. Create a template with the starter-kit:

    npx degit rpgjs/template my-rpg-game
    cd my-rpg-game
    npm install
    npm run dev

2. Edit `src/server/player.ts` to display a choice when a player joins the map

```
      async onJoinMap(map: RpgMap) {
        const choice = await this.showChoices('What color do you prefer?', [
         { text: 'Black', value: 'black' },
         { text: 'Rather the blue', value: 'blue' },
         { text: 'I don\'t have a preference!', value: 'none' }
        ]);
      }
```

3. Reload `http://localhost:3001/`, you see the choice menu correctly displays but the player is no longer controllable at exit.
4. Now add a line `await this.showText('Hello World');` at the end of `onJoinMap` and save.
5. Reload `http://localhost:3001/`, the choice menu displays first, then the "Hello World" message at exit and then you can still move the player.
 
(so a workaround for this bug is to always call a `showText` after an `showChoices`, which maybe we want to do in practice anyway...)

**Comment by RSamaium** [comment]
Fixed on the update (alpha.10)
