### ISSUE TITLE
pre-built showChoices UI is not working well on mobile

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#85]
On mobile:

- One cannot use tap gesture to select an option.
- One can use the `nipplejs` joystick to move up and down, but this is too sensitive and cursor is moving too fast.

A workaround is to implement a custom UI with an "Up" and "Down" button, similar to the "Action" one. But it would be nice to have a better UI by default.

**Comment by RSamaium** [comment]
Fixed on the update (alpha.10)
