### ISSUE TITLE
Sound's loop property has no effect

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#87]
1. Open https://rpgjs.dev/ (or the default template)
2.  Listen to the music for a duration of 3 minutes and 12 seconds
3. Music stops.

However per https://docs.rpgjs.dev/classes/sound.html#loop and because the starter-kit uses loop: true, music should be restarted.

**Comment by RSamaium** [comment]
Fixed on the update (alpha.10)
