### ISSUE TITLE
Errors in non-browserSync mode http://localhost:3000

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#92]
When running with non-browserSync mode, I often get errors with failed load e.g. with the rpgjs demo

    Uncaught TypeError: resource is undefined
        RpgSound http://localhost:3000/bundle.js:71522
        complete http://localhost:3000/bundle.js:71172
        dispatch http://localhost:3000/bundle.js:52265
        _onComplete http://localhost:3000/bundle.js:37308
        _onLoad http://localhost:3000/bundle.js:37346
        next http://localhost:3000/bundle.js:35122
        use http://localhost:3000/bundle.js:41553
        _onLoad http://localhost:3000/bundle.js:37329
        next http://localhost:3000/bundle.js:35130
    bundle.js:71522:37
    Erreur dans les liens source : Error: request failed with status 404
    URL de la ressource : http://localhost:3000/bundle.js
    URL du lien source : Timeline.js.map

Or with my own program with custom spritesheet:

    Uncaught Error: [RPGJS] - Impossible to find the sphinge spritesheet. Did you put the right name or create the spritesheet?
        log http://localhost:3000/bundle.js:89143
        Animation http://localhost:3000/bundle.js:71345
        setGraphic http://localhost:3000/bundle.js:89331
        update http://localhost:3000/bundle.js:89339
        draw http://localhost:3000/bundle.js:88912
        draw http://localhost:3000/bundle.js:71192
        draw http://localhost:3000/bundle.js:82346
        renderLoop http://localhost:3000/bundle.js:81689
    bundle.js:89143:12
        log http://localhost:3000/bundle.js:89143
        Animation http://localhost:3000/bundle.js:71345
        setGraphic http://localhost:3000/bundle.js:89331
        update http://localhost:3000/bundle.js:89339
        draw http://localhost:3000/bundle.js:88912
        draw http://localhost:3000/bundle.js:71192
        draw http://localhost:3000/bundle.js:82346
        renderLoop http://localhost:3000/bundle.js:81689
    Erreur dans les liens source : Error: request failed with status 404
    URL de la ressource : http://localhost:3000/bundle.js
    URL du lien source : Timeline.js.map

If I run in dev mode or if I force a refresh with Ctr+Maj+R, it works normally.

**Comment by fred-wang** [comment]
(testing in Firefox on Linux)

**Comment by RSamaium** [comment]
I can't reproduce the bug. To check that the latest version if the problem is still present

**Comment by fred-wang** [comment]
I still see it with the latest version. In Firefox, not in Chrome though.

Uncaught TypeError: resource is undefined
    RpgSound http://localhost:3000/bundle.js:71522
    complete http://localhost:3000/bundle.js:71172
    dispatch http://localhost:3000/bundle.js:52265
    _onComplete http://localhost:3000/bundle.js:37308
    _onLoad http://localhost:3000/bundle.js:37346
    next http://localhost:3000/bundle.js:35122
    use http://localhost:3000/bundle.js:41553
    _onLoad http://localhost:3000/bundle.js:37329
    next http://localhost:3000/bundle.js:35130
    setTimeout handler*next http://localhost:3000/bundle.js:35129
    use http://localhost:3000/bundle.js:44422
    _onLoad http://localhost:3000/bundle.js:37329
    next http://localhost:3000/bundle.js:35130
    setTimeout handler*next http://localhost:3000/bundle.js:35129
    use http://localhost:3000/bundle.js:37485
    _onLoad http://localhost:3000/bundle.js:37329
    next http://localhost:3000/bundle.js:35130
    setTimeout handler*next http://localhost:3000/bundle.js:35129
    parsing http://localhost:3000/bundle.js:36661
    _onLoad http://localhost:3000/bundle.js:37329
    next http://localhost:3000/bundle.js:35130
    setTimeout handler*next http://localhost:3000/bundle.js:35129
    eachSeries http://localhost:3000/bundle.js:35135
    _onLoad http://localhost:3000/bundle.js:37328
    dispatch http://localhost:3000/bundle.js:52265
    _finish http://localhost:3000/bundle.js:35888
    complete http://localhost:3000/bundle.js:35707
    _loadElement http://localhost:3000/bundle.js:35917
    load http://localhost:3000/bundle.js:35785
    _loadResource http://localhost:3000/bundle.js:37282
    next http://localhost:3000/bundle.js:35122
    eachSeries http://localhost:3000/bundle.js:35135
    _loadResource http://localhost:3000/bundle.js:37271
    _boundLoadResource http://localhost:3000/bundle.js:36781
    process http://localhost:3000/bundle.js:35214
    resume http://localhost:3000/bundle.js:35242
    load http://localhost:3000/bundle.js:37206
    load http://localhost:3000/bundle.js:71150
    loadScene http://localhost:3000/bundle.js:82374
    __awaiter http://localhost:3000/bundle.js:82257
    __awaiter http://localhost:3000/bundle.js:82253
    loadScene http://localhost:3000/bundle.js:82350
    _initSocket http://localhost:3000/bundle.js:81852
    emit http://localhost:3000/bundle.js:57482
    emit http://localhost:3000/bundle.js:75790
    emitEvent http://localhost:3000/bundle.js:75461
    onevent http://localhost:3000/bundle.js:75448
    onpacket http://localhost:3000/bundle.js:75412
    emit http://localhost:3000/bundle.js:57482
    emitReserved http://localhost:3000/bundle.js:75803
    ondecoded http://localhost:3000/bundle.js:74594
    emit http://localhost:3000/bundle.js:57482
    add http://localhost:3000/bundle.js:66854
    ondata http://localhost:3000/bundle.js:74586
bundle.js:71522:37

**Comment by fred-wang** [comment]
OK, I went to Firefox and cleared the site data registered for localhost. Now I no longer see the bug.

Thanks!
