### ISSUE TITLE
Bad display when calling setGraphic twice.

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#93]
1. Clone the default template
2. Add a command in `player.ts` to change the hero's graphic e.g.
```
        onInput({ input }) {
            if (input == Control.Back) {
                this.setGraphic('female13')
            }
        }
```
3. Run the game and press Escape. You see the two graphics (male and female characters) overlapping. However, if you reload the page, only the female character is displayed.

**Comment by RSamaium** [comment]
Fixed on the update (alpha.10)

**Comment by fred-wang** [comment]
Thanks!
