### ISSUE TITLE
Repeated calls to teleport('my-shape-name') no longer selects a position randomly

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#96]
From https://docs.rpgjs.dev/commands/common.html#teleport-on-the-map : 

"If you have several shapes with the same name, one position will be chosen randomly."

In 3.0.0-alpha.7, repeated calls to `teleport` would randomly select one position at each call.

In 3.0.0-alpha.10, it seems that the selected position is always the same.

**Comment by RSamaium** [comment]
Fixed on alpha.12 version
