### ISSUE TITLE
Configuration of htmlWebpackPlugin.options.title

### ISSUE THREAD

**Issue by fred-wang** [RSamaium/RPG-JS#97]
The page `src/index.html` takes its title from the configuration `htmlWebpackPlugin.options.title`, but explanation of https://docs.rpgjs.dev/guide/webpack.html#put-webpack seems complicate.

Checking `node_modules/@rpgjs/compiler/webpack-client.js`, it actually takes the title from the title value of an `rpg.json` file, if present.

Is it actually a bug or an undocumented feature ? Shouldn't it try and take the title from `rpgjs.json` instead ? Maybe building it from the `name` value?

Note: with the starter kit, you can check that "My RPG Game" will be used (from `webpack-client.js`) rather than "My Game" (from `rpgjs.json`).

**Comment by RSamaium** [comment]
Yes, it is,

Just an error in the property in the JSON. It is not `name` but `title`

https://github.com/rpgjs/template/blob/master/rpgjs.json#L2

**Comment by RSamaium** [comment]
Corrected by keeping the `name` property.

The real problem is that the file name must be `rpg.json`  :disappointed:
