### ISSUE TITLE
Can't buy key in sample3 demo (also not possible on rpgjs.dev)

### ISSUE THREAD

**Issue by eternityslyre** [RSamaium/RPG-JS#98]
I've been enjoying playing around with RPG-JS so far, but found that it doesn't compile with the most recent commits, and also that I am entirely unable to buy or sell anything! If this functionality isn't yet available, could it be documented somewhere to let prospective users know?

**Comment by RSamaium** [comment]
Thanks for your feedback. I'll look into it. 

Feel free to give me more feedback if you find any problems ;)

**Comment by eternityslyre** [comment]
Glad my feedback is appreciated! Here's the output from running "npm run dev" from the project root:

8:58:37 AM - Starting compilation in watch mode...
[watch:server]
[watch:database]
[watch:database] 8:59:40 AM - Found 0 errors. Watching for file changes.
[watch:common]
[watch:common] 8:59:41 AM - Found 0 errors. Watching for file changes.
[sample]
[sample] webpack is watching the files...
[sample]
[watch:testing] src/index.ts(1,24): error TS2307: Cannot find module '@rpgjs/common'.
[watch:testing] src/index.ts(2,28): error TS2307: Cannot find module '@rpgjs/server'.
[watch:testing] src/index.ts(3,48): error TS2307: Cannot find module '@rpgjs/client'.
[watch:testing]
[watch:testing] 9:00:18 AM - Found 3 errors. Watching for file changes.
[watch:server] src/Enemy.ts(32,14): error TS2339: Property 'graphic' does not exist on type 'RpgEnemy'.
[watch:server] src/Event.ts(2,34): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Game/Map.ts(1,38): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Game/Map.ts(94,14): error TS2339: Property 'getShapes' does not exist on type 'RpgMap'.
[watch:server] src/Game/Map.ts(98,14): error TS2339: Property 'getShapes' does not exist on type 'RpgMap'.
[watch:server] src/Game/Map.ts(121,21): error TS2339: Property 'getShapes' does not exist on type 'RpgMap'.
[watch:server] src/Game/Map.ts(147,40): error TS2339: Property 'tileWidth' does not exist on type 'RpgMap'.
[watch:server] src/Game/Map.ts(148,42): error TS2339: Property 'tileHeight' does not exist on type 'RpgMap'.
[watch:server] src/Game/Map.ts(167,27): error TS2339: Property 'id' does not exist on type 'RpgEvent'.
[watch:server] src/Gui/BattleGui.ts(12,14): error TS2339: Property 'on' does not exist on type 'BattleGui'.
[watch:server] src/Gui/DialogGui.ts(1,29): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Gui/DialogGui.ts(39,31): error TS2339: Property 'direction' does not exist on type 'RpgPlayer'.
[watch:server] src/Gui/DialogGui.ts(62,23): error TS2339: Property 'direction' does not exist on type 'RpgPlayer'.
[watch:server] src/Gui/Gui.ts(2,30): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Gui/MenuGui.ts(1,29): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Gui/MenuGui.ts(12,14): error TS2339: Property 'on' does not exist on type 'MenuGui'.
[watch:server] src/Gui/ShopGui.ts(1,29): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Gui/ShopGui.ts(22,14): error TS2339: Property 'on' does not exist on type 'ShopGui'.
[watch:server] src/Gui/ShopGui.ts(30,14): error TS2339: Property 'on' does not exist on type 'ShopGui'.
[watch:server] src/Monitor/index.ts(1,30): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/BattleManager.ts(1,24): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/BattleManager.ts(9,24): error TS2307: Cannot find module '@rpgjs/database'.
[watch:server] src/Player/ClassManager.ts(1,24): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/EffectManager.ts(1,24): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/EffectManager.ts(2,24): error TS2307: Cannot find module '@rpgjs/database'.
[watch:server] src/Player/ElementManager.ts(1,24): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/ElementManager.ts(107,22): error TS2339: Property 'elements' does not exist on type 'ItemModel'.
[watch:server] src/Player/ElementManager.ts(108,50): error TS2339: Property 'elements' does not exist on type 'ItemModel'.
[watch:server] src/Player/ItemManager.ts(1,24): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/ItemManager.ts(2,24): error TS2307: Cannot find module '@rpgjs/database'.
[watch:server] src/Player/ItemManager.ts(380,18): error TS2339: Property 'consumable' does not exist on type 'ItemModel'.
[watch:server] src/Player/ItemManager.ts(383,30): error TS2339: Property 'hitRate' does not exist on type 'ItemModel'.
[watch:server] src/Player/MoveManager.ts(1,27): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/MoveManager.ts(2,23): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/MoveManager.ts(5,23): error TS2307: Cannot find module '@rpgjs/sync-server'.
[watch:server] src/Player/MoveManager.ts(150,50): error TS2339: Property 'getDirection' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(155,33): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(155,53): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(164,33): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(164,53): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(176,50): error TS2339: Property 'getDirection' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(181,33): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(181,53): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(190,33): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/MoveManager.ts(190,53): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/ParameterManager.ts(1,23): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/Player.ts(1,76): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/Player.ts(167,34): error TS2339: Property 'emit' does not exist on type 'Gui'.
[watch:server] src/Player/Player.ts(204,14): error TS2339: Property 'graphic' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(237,19): error TS2339: Property 'hitbox' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(293,14): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(334,14): error TS2339: Property 'position' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(336,18): error TS2339: Property 'map' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(426,34): error TS2339: Property 'map' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(443,28): error TS2339: Property 'playerId' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(453,32): error TS2339: Property 'mapInstance' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(507,28): error TS2339: Property 'playerId' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(528,36): error TS2339: Property 'map' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(543,32): error TS2339: Property 'map' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(546,31): error TS2339: Property 'map' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/Player.ts(591,28): error TS2339: Property 'playerId' does not exist on type 'RpgPlayer'.
[watch:server] src/Player/SkillManager.ts(1,24): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Player/SkillManager.ts(2,24): error TS2307: Cannot find module '@rpgjs/database'.
[watch:server] src/Player/StateManager.ts(1,24): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Query.ts(1,23): error TS2307: Cannot find module '@rpgjs/sync-server'.
[watch:server] src/Query.ts(2,23): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Query.ts(50,78): error TS2339: Property 'id' does not exist on type 'RpgPlayer'.
[watch:server] src/RpgServer.ts(1,28): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Scenes/Map.ts(2,30): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/Scenes/Map.ts(3,23): error TS2307: Cannot find module '@rpgjs/sync-server'.
[watch:server] src/Scenes/Map.ts(64,57): error TS2339: Property 'tileHeight' does not exist on type 'RpgMap'.
[watch:server] src/Scenes/Map.ts(65,55): error TS2339: Property 'tileWidth' does not exist on type 'RpgMap'.
[watch:server] src/Scenes/Map.ts(66,61): error TS2339: Property 'tileHeight' does not exist on type 'RpgMap'.
[watch:server] src/Scenes/Map.ts(67,61): error TS2339: Property 'tileWidth' does not exist on type 'RpgMap'.
[watch:server] src/entry-point.ts(1,68): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/index.ts(2,89): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/models/Item.ts(1,29): error TS2307: Cannot find module '@rpgjs/database'.
[watch:server] src/presets/index.ts(1,23): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server] src/server.ts(6,23): error TS2307: Cannot find module '@rpgjs/sync-server'.
[watch:server] src/server.ts(7,57): error TS2307: Cannot find module '@rpgjs/common'.
[watch:server]
[watch:server] 9:00:19 AM - Found 80 errors. Watching for file changes.
[watch:sync-client]
[watch:sync-client] 9:00:40 AM - Found 0 errors. Watching for file changes.
[sample] [nodemon-webpack-plugin]: Compilation error.
[watch:client] src/Effects/Animation.ts(1,23): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/KeyboardControls.ts(1,23): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/Presets/AnimationSpritesheet.ts(1,27): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/Renderer.ts(3,39): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/RpgClient.ts(2,28): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/RpgClientEngine.ts(6,23): error TS2307: Cannot find module '@rpgjs/sync-client'.
[watch:client] src/RpgClientEngine.ts(16,8): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/Scene/Battle.ts(1,32): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/Scene/Map.ts(1,53): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/Scene/Scene.ts(1,39): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/Sprite/Character.ts(1,34): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/Tilemap/index.ts(1,23): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/clientEntryPoint.ts(1,68): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/index.ts(1,80): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client] src/index.ts(3,28): error TS2307: Cannot find module '@rpgjs/common'.
[watch:client]
[watch:client] 9:01:09 AM - Found 15 errors. Watching for file changes.
^C[watch:sync-client] npm run watch:sync-client exited with code SIGINT
[watch:database] npm run watch:database exited with code SIGINT
[watch:server] npm run watch:server exited with code SIGINT
[watch:client] npm run watch:client exited with code SIGINT
[watch:testing] npm run watch:testing exited with code SIGINT
[watch:common] npm run watch:common exited with code SIGINT
[watch:sync-server] npm run watch:sync-server exited with code SIGINT
[sample] cd packages/sample3 && npm run dev exited with code SIGINT

**Comment by RSamaium** [comment]
If you use the current version (under development), remember to install the dependencies:

```
npm install
npx lerna bootstrap
```

**Comment by RSamaium** [comment]
Key item problem fixed in version 3.0.0-alpha.13
