### ISSUE TITLE
Support for the HTML5 Gamepad API

### ISSUE THREAD

**Issue by mpathy** [RSamaium/RPG-JS#99]
I would like to see support for the Gamepad API.

Every current browser supports it: https://caniuse.com/?search=Gamepad 

https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API
https://developer.mozilla.org/en-US/docs/Web/API/Gamepad_API/Using_the_Gamepad_API

I think it would be great for this kind of games, to have an easy access using the gamepad.
All the classic rpg games we are fond of, did run on a system with only controllers.

If I understand the architecture more, I maybe could provide a patch, but currently I only want to report it as a feature request.
And keep track on it and the interest.

**Comment by RSamaium** [comment]
thanks a lot for the feedback. i thought of adding the gamepad but there are other features to do before.

Indeed, if you want, you can do it (take the last version of RPGJS)

1. You have to create a module

https://docs.rpgjs.dev/guide/create-module.html

You can generate it:

`npx rpgjs generate module <directory-name>`

2. In the generated folder, put a package.json (`npm init`)

3. You can then test the module in your game. Just use the properties and hooks of the client (https://docs.rpgjs.dev/classes/client.html#rpgclient-decorator).

4. Then, just publish the package

Help:

When you press a key on the gamepad, use the method `applyControl` (https://docs.rpgjs.dev/classes/keyboard.html#apply-control)
You can also look at the module that manages joystick on the mobile.

https://github.com/RSamaium/RPG-JS/tree/v3/packages/plugins/mobile-gui

Of course, in case you do this module, I will not hesitate to quote you in the RPGJS project ;)

**Comment by RSamaium** [comment]
The plugin is present in the latest version

https://docs.rpgjs.dev/guide/gamepad.html
